$domain = "howielab.local"
$domain_ip_address = "10.1.2.5"
$s1_linux_deb_agent = "SentinelAgent_linux_v4_1_1_3.deb"
$s1_site_token = "eyJ1cmwiOiAiaHR0cHM6Ly91c2VhMS1wdXJwbGUuc2VudGluZWxvbmUubmV0IiwgInNpdGVfa2V5IjogIjZiODA5ZGI0YjQ3YzhkY2YifQ=="
$N = 1


Vagrant.configure("2") do |config|

    config.vm.provider :virtualbox do |v, override|
        v.linked_clone = true
        v.cpus = 2
        v.customize ["modifyvm", :id, "--clipboard-mode", "bidirectional"]
    end

    (1..$N).each do |i|

        config.vm.define "ubuntu-#{i}" do |node|
            node.vm.provider :virtualbox do |v, override|
                v.memory = 2048
                v.gui = true
            end
            node.vm.box = "ubuntu/bionic64"
            node.vm.hostname = "ubuntu.#{$domain}"
            node.vm.network "private_network", ip: "10.1.2.#{i + 200}"
            node.vm.provision "shell", path: "provision/provision-base.sh"
            node.vm.provision "shell", path: "provision/install-metasploit.sh"          
            node.vm.provision "reload"
        end

    end

end
